name: EXAMEN

on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: PHPUnit Tests
        uses: php-actions/phpunit@v1
        env:
          TEST_NAME: examenTest
        with:
          configuration: tests/phpunit.xml
          args: --coverage-text
  cd:
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - uses: actions/checkout@v1
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build
        run: |
          docker build -t ${{ secrets.DOCKER_USER }}/examen:${{ github.sha }} .
          docker build -t ${{ secrets.DOCKER_USER }}/examen:latest .
        #- name: Tags
         # run: |
          #  docker tag back ${{ secrets.DOCKER_USER }}/examen:${{ github.sha }}
           # docker tag back ${{ secrets.DOCKER_USER }}/examen:latest
      - name: Push
        run:  |
          docker push ${{ secrets.DOCKER_USER }}/examen:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USER }}/examen:latest  
